server {
    listen 3000;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: all routes fallback to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
